// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svatfdkvpbtcefblidzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2YXRmZGt2cGJ0Y2VmYmxpZHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjQ3ODUsImV4cCI6MjA2NjM0MDc4NX0.d1fxiyuJ_oM_ND2fw_TkjBGFPQbPssNew3BZnRW-ALU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);