// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufrckcjsxhvvzmwcrrrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmcmNrY2pzeGh2dnptd2NycnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzMzODIsImV4cCI6MjA2NjM0OTM4Mn0.OEU15Do_iYb9-nbOnKsacCeFGWlQtnobkopH3_owBi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);